### PR TITLE
Switch `mstart` from being a local variable to the one stored in `amr_module`

### PR DESCRIPTION
**Pull request by mandli**
This appears to be an issue when the f90 refactor occurred.  This fixes that.

### CODE REVIEW

**Comment by mandli** [comment]
Note that at this point I cannot get this to pass the tests but it looks like it has something to do with the adjoint tests and I am having difficulty understanding why.

**Comment by mjberger** [comment]
shoudln't have anything to do with it.  There must a different thing going on - versionitis?

 — Marsha

**Comment by mandli** [comment]
I agree and it looks like Travis is passing so I think this is probably safe to merge.

**Comment by rjleveque** [comment]
What test isn't passing?  I tried this and it seems to work fine for me, both all the tests and `examples/acoustics_1d_adjoint`.

**Comment by rjleveque** [comment]
As far as I can see, the only place mstart is used in these subroutines is in  `call outtre(mstart,.false.,nvar,naux)` immediately before `stop` in the case of an error, so I don't see this change can affect cases that are running properly.

**Comment by mandli** [comment]
I agree but it's better to have it fixed.  I think my own testing is messed up right now as well so I would not worry about it if this looks good.

**Pull request merged**
