### PR TITLE
change initial size of alloc array from 1M to 4M

### PR DESCRIPTION
**Pull request by rjleveque**
The initial size is often too small and these days a bigger allocation
seems reasonable

### CODE REVIEW

**Comment by mandli** [comment]
This is fine by me although I was wondering if there is a reason to not make it a power of 2 as it might fit better in hardware caches maybe?

**Comment by mjberger** [comment]
I don't think it matters, since the actual storage chunks used by the grid patches won't be powers of 2.

 — Marsha

**Comment by rjleveque** [comment]
@mandli: Are you ok with merging this?  

@berger and I would like to increase the defaults also of maxgr and don't think powers of 2 matter.

**Comment by mandli** [comment]
Fine with me.

**Pull request merged**
