### PR TITLE
Refactor `valout` routine

### PR DESCRIPTION
**Pull request by mandli**
This refactor is the basis of an effort to add other output formats, in particular either HDF5, SILO, and/or NetCDF.

### CODE REVIEW

**Comment by mandli** [comment]
This PR now incorporates the recording of timing as outlined in clawpack/geoclaw#280.  A couple of things:
 - Does the output look ok?
 - It was mentioned that we may want to also move the timing from `fort.amr` to it's own file as well.

Once this is figured out we can also add this to GeoClaw.

**Comment by rjleveque** [comment]
Yes, I think what now appears at the end of `fort.amr` with overall timing info could go to a new file `timing.txt`.

I like the `timing.csv` format, but it seems like a column is missing for total wall time?

I will update my `plot_timing_stats.py` from #280 to read in this file.

The original point of this PR was to support HDF5, is this part fully working?

**Comment by mandli** [comment]
- I will modify this PR to pipe the output into a file called `timing.txt`.
 - I thought total wall time was being recorded, will look.
 - It was but I think all of this works independently of that right now and I think it’s better merge than to wait for that to happen.

**Comment by rjleveque** [comment]
We also need a column in `timings.csv` for the simulation time (the value printed to `fort.t*`) at each output time, since the plots show e.g. CPU time vs. simulation time.

**Comment by mandli** [comment]
Does the line `call cpu_time(t_CPU_overall)` not get the simulation time?

**Comment by mandli** [comment]
I modified the end of `amr*.f90` to output to a separate file.

**Comment by rjleveque** [comment]
Don't merge until https://github.com/mandli/amrclaw/pull/2 is merged in to this.

**Comment by rjleveque** [comment]
I am going to merge this, but at some point more work is needed to make restarting timers work in 1d and 3d, see #219.

**Pull request merged**
