### PR TITLE
Moment Function Refactor to Prevent Bad Optimization

### PR DESCRIPTION
**Pull request by mandli**
@mjberger and I traced down what we think was the problem in https://github.com/clawpack/geoclaw/issues/247 where the error
```
 ***  double flux update CAN happen in upbnd ***
```
was sometimes being printed.  It turned out that this section in the `moment` function
```fortran
       do 80 ipt = 1, npt
           if (badpts(1,ipt) .gt. emx1) emx1 = badpts(1,ipt)
           if (badpts(1,ipt) .lt. emn1) emn1 = badpts(1,ipt)
           if (badpts(2,ipt) .gt. emx2) emx2 = badpts(2,ipt)
           if (badpts(2,ipt) .lt. emn2) emn2 = badpts(2,ipt)
  80   continue
```
was admitting wrong maxima and minima when certain optimization flags were turned on.  This PR refactors the `moment` function and uses some F90 intrinsics to do the above.  In the test cases I ran this seems to have corrected the problem in `upbnd` as the bad results from this routine were mucking about with removed points and therefore the refinement.

### CODE REVIEW

**Comment by mjberger** [comment]
Please note though that this was a compiler bug, Kyle found it in 17.0 ifort for example, but
it was fixed by 17.2

Same for previous versions of the compiler.

 — Marsha

**Comment by mandli** [comment]
So we may have another problem.  The tests for both geoclaw and amrclaw pass when using GCC with even aggressive optimization on but they are having issues with the intel compiler.  This time though I am getting
```
 nestck1: 1 pt. cluster at level     3 still not nested
          pt. too close to boundary
 non-nested flagged pt. at:   0.4550000E+02
```
while running the acoustics_1d_homogeneous **test**.  Investigating still.

**Comment by mandli** [comment]
Oh, and GeoClaw seems to pass fine using the intel compiler.

**Comment by mandli** [comment]
It looks like advection_1d_example1 also fails with
```
there are    1 grids with       40 cells at level   1
 nestck1: 1 pt. cluster at level     3 still not nested
          pt. too close to boundary
 non-nested flagged pt. at:   0.5150000E+02
```

**Comment by mandli** [comment]
Can someone who has worked on the 1D AMR code look at this?  This is a pretty critical fix and I am not sure whether what's being done in 1D is more broadly flawed or if we just need to look at the examples that are failing.

**Comment by mandli** [comment]
The errors seems to have mystically disappeared.

**Comment by mandli** [comment]
Now I am getting this error again in the same 1D example:
```
there are    1 grids with       40 cells at level   1
 nestck1: 1 pt. cluster at level     3 still not nested
          pt. too close to boundary
 non-nested flagged pt. at:   0.4550000E+02
```

**Comment by mandli** [comment]
Can we take another look at this?  We are seeing this problem in our version of the intel compiler on our cluster.

**Comment by rjleveque** [comment]
Yes, I also get this non-nested error in `examples/advection_1d_example1` when I compile with ifort version 14.0.2 with
```
FFLAGS = -g -check all -traceback -fpe0 -ftrapuv -fp-model precise
```
@mjberger pointed out this was due to a compile bug that was fixed in 17.2, but I don't have access to that.  @mandli: what compiler version are you using?

It would be nice if there's a fix to make it work with older compiler versions?

**Another issue:** Maybe also a compiler issue, but if I try to compile with ifort using
```
FFLAGS = -O2 -openmp
```
Then it won't even compile, complaining about this:
```
/home/rjl/git/clawpack/amrclaw/src/1d/advanc.f(54): error #5082: Syntax error, found 'ALLOC' 
when expecting one of: <IDENTIFIER> <CHAR_CON_KIND_PARAM> <CHAR_NAM_KIND_PARAM> <CHARACTER_CONSTANT> /
!$OMP&            SHARED(level, nvar, naux, alloc, intrat, delt,
--------------------------------------------^
/home/rjl/git/clawpack/amrclaw/src/1d/advanc.f(101): error #5082: Syntax error, found 'ALLOC' 
when expecting one of: <IDENTIFIER> <CHAR_CON_KIND_PARAM> <CHAR_NAM_KIND_PARAM> <CHARACTER_CONSTANT> /
!$OMP&            SHARED(rvol,rvoll,level,nvar,mxnest,alloc,intrat)
------------------------------------------------------^
```

Maybe because `alloc` comes from `amr_module` and we just `use amr_module` without specifying `only:...`?  But `intrat` also comes from there.

**Comment by mandli** [comment]
Huh, never have run into that.  I do vaguely recall running into something weird like this for another variable but I don't remember how I got around that.  Maybe newer versions of OpenMP allow that?  I also made a request to our HPC team to see if we can update the compiler to the newest in the 17 line.

**Comment by mjberger** [comment]
the problem was also a compiler bug, due to the word “alloc” which must also be some kind of reserved word.    Next version of compiler did not have that problem.

Marsha

**Pull request merged**
