### PR TITLE
Remove timeSetaux variables

### PR DESCRIPTION
**Pull request by mandli**
Addresses #208.

### CODE REVIEW

**Comment by rjleveque** [comment]
The tests are failing because `timeSetaux` and `timeSetauxCPU` are also used in other subroutines from which they need to be removed: amr3.f90, errest.f, filpatch.f, gfixup.f, saveqc.f.

**Comment by mandli** [comment]
Huh, no idea why my compiler caught the `ginit` problem but not the others.  Are these all ok to remove?

**Comment by rjleveque** [comment]
Maybe you had a stale .mod file?

OK to remove as far as I know, they seem to all be gone from the 2d version.

**Comment by mandli** [comment]
Oh, that could be.  In any case I removed the rest  of the  offending variables, hopefully it works now.

**Pull request merged**
