### PR TITLE
Refactor boundary condition function

### PR DESCRIPTION
**Pull request by mandli**
This PR refactors the boundary condition code similar to what was done in clawpack/geoclaw#285.

### CODE REVIEW

**Comment by mandli** [comment]
Left to do is the 1D and 3D codes.  Once the 2D code seems good I will move to modify the other two.

**Comment by rjleveque** [comment]
Looks good.  I ran all the `examples` and they give the expected results (except `euler_1d_wcblast` which fails for some unrelated reason that I will investigate).

At some point we should also replace
 - `examples/advection_2d_inflow/bc2amr.f`
 - `examples/advection_3d_inflow/bc3amr.f`

with updated .f90 versions based on this.

@mjberger should review.

**Comment by mjberger** [comment]
Looks good to me.  Go ahead.

Marsha

**Comment by mandli** [comment]
Tests pass (there were a couple of bugs in 1D) and this now also includes 3D and the example specific code although I was not able to compare the 3D runs as I do not have matlab.

**Pull request merged**
