### PR TITLE
WIP: 1d adaptive mesh refinement

### PR DESCRIPTION
**Pull request by BrisaDavis**
Note: this is work in progress.

This branch has 1d adaptive mesh refinement code that I believe to be working correctly.

### CODE REVIEW

**Comment by mandli** [comment]
If you need help writing a test based on your example let me know.

**Comment by BrisaDavis** [comment]
That would be wonderful, how would I go about writing a test for it?

**Comment by mandli** [comment]
Take a look at the other tests in AMRClaw, GeoClaw, or Classic.  Classic may be where you would want to start as that is the simplest.  In any case youWr

**Comment by rjleveque** [comment]
This was replaced by #191, which has been merged, so I am closing this PR.
Thanks again @BrisaDavis for all the work on this!

**Pull request closed without merging**
