### PR TITLE
Refactored dumpgauge as print_gauges, in gauges_module, added gauges in 3d

### PR DESCRIPTION
**Pull request by rjleveque**
I plan to add gauges to 3d amrclaw but first suggest these changes:

I renamed `dumpgauge` to `print_gauges` and changed the algorithm. 

Previously `setbestsrc` determined which patch to use for each gauge and then applied quicksort so that all the gauges for a particular patch were grouped together.  Then in `dumpgauge`, a binary search was done to find the first gauge to handle and then the loop only went until the gauge number changed.  

I changed it so that no sorting is done.  Instead in `print_gauges`,  when called for each patch it loops over all gauges and simply skips the ones for which this patch is not the best.  If there were thousands of gauges this might be slightly slower than the sorting, but typically there are at most a handful and I think calling the binary search is probably much slower than simply looping over all gauges.  Even with a huge number of gauges, I think the time sink in this routine would be the I/O, not the loop over all gauges.   The new version is much simpler and easier to maintain.

@berger, do you agree?

I modified all the examples and tests and everything agrees.  Note that `examples/compare_gauges.py` uses visclaw#137, a new utility that might be useful in general (I've written many versions of this in the past).

One possible change in the `fort.gauge` files produced:  The gauges at a particular time might be printed in a different order than before since sorting is not done.  The values printed should be identical, but the `fort.gauge` file may have permuted lines relative to old output. 

I'm also adding Issue #117 regarding possible future improvements.

### CODE REVIEW

**Comment by rjleveque** [comment]
@mjberger convinced me to restore the quick sort of gauges.  I've reverted that, but then modified setbestsrc to keep track of the range of gauges that each grid must handle, using new module variables mbestg1 and mbestg2.  So now, when looping over grids, there is no need for a call to the binary search from each grid every time step.

**Comment by rjleveque** [comment]
@mjberger:  My most recent commit has a first pass at 3d gauges but isn't working because in `amr_module.f90`, the `alloc` variable is declared via

```
    real(kind=8), pointer, dimension(:) :: alloc
```

In the 2d code, it is declared as....

```
    real(kind=8), allocatable, dimension(:) :: alloc    ! new way, use allocatable, not pointer
```

Can I just make this change in 3d or does something else need to be changed?

The error message I get is...

```
$ cd /Users/rjl/git/clawpack/amrclaw/examples/advection_3d_inflow/

$ make .exe
gfortran -c /Users/rjl/git/clawpack/amrclaw/src/3d/advanc.f               -I/Users/rjl/git/clawpack/amrclaw/src/3d/ -I/Users/rjl/git/clawpack/amrclaw/examples/advection_3d_inflow/  -O2 -fopenmp -o /Users/rjl/git/clawpack/amrclaw/src/3d/advanc.o
/Users/rjl/git/clawpack/amrclaw/src/3d/advanc.f:231.27:

         call print_gauges(alloc(locnew),alloc(locaux),xlow,ylow,zlow,  
                           1
Error: Element of assumed-shaped or pointer array passed to array dummy argument 'q' at (1)
```

**Comment by mandli** [comment]
Doesn't the first version mean you want an array of pointers?

**Comment by rjleveque** [comment]
When I just change "pointer" to "allocatable" it compiles and seems to run fine so far...

**Comment by rjleveque** [comment]
I take it back, I forgot to "make new".  

```
/Users/rjl/git/clawpack/amrclaw/src/3d/init_alloc.f90:19.10:
          alloc => storage
          1
Error: Non-POINTER in pointer association context (pointer assignment) at (1)
```

We have to get rid of the `storage` array as was done in 2d.

**Comment by rjleveque** [comment]
I just added a regression test in 3d, and have tested this pretty well in both 2d and 3d and @cjvogl has also been using in 3d.  I think it's ready to merge?

**Comment by mandli** [comment]
This all looks good to me.  Thanks for the effort @rjleveque and @cjvogl!

**Pull request merged**
