### PR TITLE
Fix restart frame number when output_t0 is True

### PR DESCRIPTION
**Pull request by rjleveque**
Fix src/Nd/restrt.f so that frame number is not advanced if output_t0 is True
    
    In this case it re-writes the last frame from the original calculation
    when restarting, and it should reuse that frame number.  For historical
    reasons the frame number is called matlabu, stored in amr_module.f90

### CODE REVIEW

**Comment by mjberger** [comment]
it's not correct. I was about to comment.

Can you regress?
 — Marsha

**Comment by mjberger** [comment]
gives wrong frame number in the output_t0 case false.

 — Marsha

**Comment by mandli** [comment]
Does `amr2` need to be modified?

**Comment by mjberger** [comment]
that's how I did it, but I"m trying to fix it without that using only restrt.

I have a meeting. I"ll have to do it this afternoon.

 — Marsha

**Comment by mandli** [comment]
Reverting this for the time being along with the equivalent GeoClaw PR then.

**Pull request merged**
