### PR TITLE
Fix local flag2refine1.f90 in euler_1d example and test

### PR DESCRIPTION
**Pull request by rjleveque**
To match changes made earlier in the library version.

### CODE REVIEW

**Comment by rjleveque** [comment]
@mandli, Do you understand why the test in  `tests/euler_1d_wcblast` is apparently not run by nosetests (by travis or on my laptop)?

**Comment by mandli** [comment]
Yeah, that directory does not have a `__init__.py` file so nosetests does not see that directory.

**Comment by mandli** [comment]
Looks like it is running that test now!

**Comment by rjleveque** [comment]
Yes, thanks!

**Pull request merged**
