### PR TITLE
Woodward-Colella blast problem using 1d amrclaw.

### PR DESCRIPTION
**Pull request by rjleveque**
setplot.py uses plot_type='pw_const' from clawpack/visclaw#216

### CODE REVIEW

**Comment by mandli** [comment]
Is there a test related to this example that we might want to also add?

**Comment by rjleveque** [comment]
I improved the example by adding a custom `flag2refine1.f90` that only checks density jumps, and uses `regions` to force refinement of the initial data near the jumps in pressure since there is initially constant density.  Also made finest levels finer to capture the solution better.

I also added a version to `tests/euler_1d_wcblast`.

**Comment by mandli** [comment]
This all looks good to me except I think you might be missing the git diff files in the test directory.

**Comment by rjleveque** [comment]
I added `claw_git_status.txt` but not `claw_git_diffs.txt`.  

I thought at one point we decided it was a bad idea to commit those since when the regression data changes the diffs show all these changes and there's a recursive problem with committing a clean copy.  But I notice most other tests subdirectories include these so maybe I dreamed it?

**Comment by mandli** [comment]
Hmm, I could see that being unwise for the diff data but claw_git_status.txt should just record the fact it was changed.  In any case I will merge this now.

**Comment by rjleveque** [comment]
@mandli:  Yes, I meant many other tests have the `claw_git_diff.txt` files and maybe at some point we'll have to remove them, but fine for now.

**Pull request merged**
