### PR TITLE
Bugfix

### PR DESCRIPTION
**Pull request by mjberger**
found flux3 bug - missing line from years ago (recovered from github). also minor index fix in outval  - a rarely used debugging routine

### CODE REVIEW

**Comment by mandli** [comment]
Can you merge in changes from master so we can merge this?

**Comment by mjberger** [comment]
On Mar 6, 2015, at 6:10 PM, Kyle Mandli <notifications@github.com> wrote:

don’t know how to get it into my bug fix branch from master. If you can call me now I”ll do it, but I have to live in 2 minutes.

marsha

**Comment by mandli** [comment]
Looks like we might need to update the regression data but we should look at this thoroughly before deciding on that action.

```
======================================================================
FAIL: Check sum of q values on each half in each direction, in frame 1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/clawpack/amrclaw/tests/advection_3d_swirl/regression_tests.py", line 73, in test2
    "\n  new_data: %s, \n  expected: %s"  % (new_data, regression_data)
AssertionError: 
  new_data: [ 30702.4520618   1297.5479382  16000.         16000.         16000.
  16000.       ], 
  expected: [ 30702.45206211   1297.54793789  16000.00000267  15999.99999733
  16000.00000002  15999.99999998]

======================================================================
FAIL: Check sum of q values on each half in each direction, in frame 2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/clawpack/amrclaw/tests/advection_3d_swirl/regression_tests.py", line 109, in test3
    "\n  new_data: %s, \n  expected: %s"  % (new_data, regression_data)
AssertionError: 
  new_data: [ 29405.1043837   2594.8956163  16000.         16000.         16000.
  16000.       ], 
  expected: [ 29405.10438486   2594.89561514  16000.00005715  15999.99994285
  16000.00000587  15999.99999413]
```

**Comment by rjleveque** [comment]
Closing this -- updated in #122.

**Pull request closed without merging**
