### PR TITLE
[WIP] Bug fix in restrt.f and issue with restarts

### PR DESCRIPTION
**Pull request by rjleveque**
@BrisaDavis found a typo in the 2d and 3d restrt.f where variable `ibuf` is read in, whereas in `amr_module.f90` it is spelled `ibuff`. (We should modify further to use `implicit none`, of course.)

I fixed this and it had no effect on the one test I did.  Presumably because `ibuff` is also read in from `amr.data` in `amr2.f90` and so this value is right (provided the user didn't change it in `setrun.py` between the two runs -- if they did, which one should prevail??).

In the process, I created the first pass at an example `examples/advection_2d_swirl_restart` showing how to do a restart and comparing the results.  (We should have such an example anyway).  There's a `README.txt` file in that directory.

@mjberger, comparing the results from a full run with no restart vs. restarting shows some minor changes in the grids chosen, below are the diffs at the next output time.  Is this expected?

Note the checkpoint file was created using `clawdata.checkpt_style == 3` so that the time step was not adjusted to hit a checkpoint time.  When I first ran it using `clawdata.checkpt_style == 2` there was more discrepancy in the results, which is not so surprising.

restart_diffs

### CODE REVIEW

**Comment by mjberger** [comment]
That’s not a bug - it’s a feature!  A  different name is used so you can change the setting if you do a restart run.  This is also done with some other variables - for example, you can also change the maximum number of levels of refinement (mxnest - mxnold), and error tolerance (tol - tl).

Why is this a problem?

As for grids changing if done with a restart, that definitely should not happen, indicates some variable not set or not exact.y set.  Call to discuss,

Marsha

**Comment by rjleveque** [comment]
I see, so the idea is that the values read in from the checkpoint file are ignored and those in `setrun.py` used instead.  This makes sense, but we should add some comments and `implicit none` at some point to make this clear.  (and document at http://www.clawpack.org/restart.html).  

So I'll revert the commit with the changes, but will leave this PR open to work on the other issue and to eventually clean up the new example and `restrt.f`.

But none of this is critical, so let's wait until after 5.3.0 is out.

**Comment by mjberger** [comment]
yes - please revert.

I don’t understand the restart issue though. If the restart isn’t at the exact same time (because of the different in checkpoint styles) then of course it won’t give exactly the same answers. That was what I thought your last email said?

I”m at work now if you want to Skype about it.

Marsha

**Comment by mjberger** [comment]
restart issue due to placement of call to checkpoint routine before the new delta t is calculated. First step upon restart used old dt information.

**Pull request closed without merging**
