### PR TITLE
fix for integer overflow in colate.

### PR DESCRIPTION
**Pull request by mjberger**
sign of comparison wrong, but main fix was years ago

### CODE REVIEW

**Comment by mandli** [comment]
I am not sure why but this seems to have failed due to a gauge discrepancy.  This might have been a hiccup on Travis so I restarted the check.  It did compile fine and only two of the tests failed.

**Comment by mjberger** [comment]
we’re working on it. Seems to have different refinement patterns.

 — Marsha

**Comment by mandli** [comment]
Gotcha.

**Comment by rjleveque** [comment]
This fixes the 7-level tsunami run that was failing before.

**Pull request merged**
