### PR TITLE
fixed bug where variable 'time' not properly declared in openmp code.…

### PR DESCRIPTION
**Pull request by mjberger**
… moved initializ. to make it private

### CODE REVIEW

**Comment by mandli** [comment]
How did this manifest?  Does this fix a bug we had found?

**Comment by mjberger** [comment]
Randy found it a few days ago for an asteroid problem with a time dependent b.c.
Perhaps we haven’t had time dependent boundary conditions before?

Marsha

**Comment by mandli** [comment]
Probably but I wonder if we never tested it with OpenMP.

**Comment by mandli** [comment]
Do you also have a fix for GeoClaw?

**Comment by mjberger** [comment]
Geoclaw did not have this problem. Neither did 3d AMR.

**Comment by mandli** [comment]
👍

**Pull request merged**
