### PR TITLE
Adding 1d amrclaw with examples and tests

### PR DESCRIPTION
**Pull request by rjleveque**
This adds new functionality - AMR in one space dimension - but I think it would be good to include in the 5.4.1 release so that it can be used, and it shouldn't break anything that was previously working.

There are 3 examples and 2 regression tests included, but it hasn't yet been well tested on challenging 1d problems.  

Thanks to @BrisaDavis for doing most of the work on this by converting the 2d code to 1d.  

Plotting gauges properly requires clawpack/pyclaw#574 and plots have legends only with clawpack/visclaw#214, but plotting shouldn't break even without that.

### CODE REVIEW

**Comment by mandli** [comment]
Why not stick this in the examples rather than in "dev" or do you want to still hold off on advertising its existence?

**Comment by rjleveque** [comment]
I didn't realize there was out-of-date stuff in the `dev` directory.  I just removed those.  The good examples are in the `examples` directory.

**Comment by mandli** [comment]
Ah sorry, I just saw a bunch of `dev/` things and thought that those were the correct ones.

**Comment by mandli** [comment]
Couple of comments:
 - The `acoustics_1d_heterogeneous/` example import `clawpack.pyclaw.io` but does not appear to use it.  I only caught this as the new ForestClaw capability includes a rename of this module but if it's not being used we should remove this line.
 - Is there a name we could use for `advection_1d_example1` rather than `example1`?  Not sure what it would be but something a bit more descriptive would be nice.
 - The tests are not being run.  I think the problem is that each of the testing directories needs to be seen by nosetests as a package and so need a `__init__.py` file in them (they can be empty).  With those the test fail but with clawpack/pyclaw#574 they pass for me.

BTW - I really like the plotting in that last example!

**Comment by rjleveque** [comment]
`advection_1d_example1` matches the name for the same example in `classic`, but eventually maybe we should rename both.

I'll fix the other things, thanks!

**Comment by mandli** [comment]
These are failing as expected due to the missing update from clawpack/pyclaw#574.  This seems ready to merge then unless you have additional things you wanted to add.

**Pull request merged**
