### PR TITLE
 Fix recording of wind at gauges (geoclaw)

### PR DESCRIPTION
**Pull request by navravi**
Summary
-------

This PR is a port of https://github.com/clawpack/geoclaw/pull/350.

Currently in amrclaw, the first time step is recorded at gauges, but the last time step is not. This behavior is the result of a workaround that introduced a bug (https://github.com/clawpack/geoclaw/issues/341) in geoclaw. Although the bug does not appear to currently affect amrclaw, we believe that it should be fixed in amrclaw as well to ease the maintenance of the two parallel code bases, as well as to avoid the possibility of a similar bug being introduced in amrclaw as a result of future changes.

Note that this PR changes how gauges are recorded. Before this PR, the first time step was recorded, but the last time step was not; after this PR, the first time step is not recorded, but the last time step is. Missing the first time step is a separate issue that should be fixed independently (after understanding why the first time step is being recorded for storm surge models in geoclaw - see https://github.com/clawpack/geoclaw/pull/350 for details).

The test outputs were overwritten as part of this change.

Testing
-------
Output of `nosetests`:
```
amrclaw (gauges)$ nosetests
.......
----------------------------------------------------------------------
Ran 7 tests in 55.082s

OK
```

### CODE REVIEW

**Comment by mandli** [comment]
Same issue as in clawpack/geoclaw#348

**Comment by mandli** [comment]
This looks good to me.  I checked the output data and everything looks fine to me but someone else should probably check this given that the testing data is changing.

**Comment by rjleveque** [comment]
Yes, mysterious how the gauge values can change in the 2nd or 3rd decimal place at some intermediate times and then go back to agreeing to all 7 digits at later times.  

Perhaps a change in whether the gauge is output before or after regridding at these times, or some such thing?  I also notice a couple places where the old gauge output is already reporting level 3 at some time while the new gauge output was still at level 2 at that same time, and otherwise all the same.

**Comment by mandli** [comment]
Focusing on the `tests.euler_1d_wcblast.regression_tests.Euler1DTest` test gauge differences I realized this was not actually being tested at all!  After that realization I was also not able to replicate the gauge data as it appears that the simulation is not refining anywhere (giving only level 1 results) and so this will fail on Travis even compared to the original data.

**Comment by rjleveque** [comment]
@mandli: The `flag2refine1.f90` in `tests/euler_1d_wcblast` doesn't have the same calling sequence as the library routine it is replacing now, since @BrisaDavis modified this in https://github.com/clawpack/amrclaw/pull/224 and I guess we didn't make that change in this test problem.  

Once I changed that, it ran and reproduced the regression data, with gauge output up to 4 levels.  The first region in `setrun.py` allows 4 levels for all time (to 1e9), so I am not sure why you only see one level of output.

And why doesn't travis (or nosetests locally) run this test?  It seems to be set up the same way as `tests/acoustics_1d_homogeneous/regression_tests.py` and that one does get run.

**Pull request merged**
