### PR TITLE
[WIP] Created regions_module for 3d.  Only basic functionality (read/write regions.data) at this point.

### PR DESCRIPTION
**Pull request by cjvogl**
This is a continuation of clawpack/amrclaw/#130.  This shouldn't affect the functionality of existing code, but allows for code in clawpack/seismic to define 3d regions for refinement.

### CODE REVIEW

**Comment by mandli** [comment]
This looks fine to me.  Note that you will want to make sure that `RegionsData` is added to the `ClawRunData` objects in `clawutil`.

In terms of what you mentioned before I think I was confused (as was @mjberger) as to what your implementation plans was.  Did you want to move the region checks outside of `flag2refine`?

**Comment by cjvogl** [comment]
Good deal, I believe ClawRunData is already set to use RegionsData properly... if it isn't, I'll repost in the next half hour.

Sorry for the confusion.  As it stands (and as far as I can tell), the 2d regions are flagged in flagregions2.f90, which is called only from bufnst2.f90.  Based off the comments in bufnst2.f90, the region flagging was once handled in/through flag2refine.f90, but has since been moved into bufbnst2.f90.

My current implementation plan for 3d regions is to use a version of flag2refine.f90 stored in the clawpack/seismic repository to handle all the region checks and potentially move this into the amrclaw repository once it's been decided where the region checks should be handled in 3d... but to do this, I need the committed updates in this PR to data.py.

Also, I'm not sure why the Travis CI build failed...

**Comment by rjleveque** [comment]
I am hoping we will get some help from @mjberger to eventually put regions in properly as in 2d.  But this won't go into the planned 5.3.0 release, so for now Chris is going to just do something simpler using a custom flag2refine.

I don't know about travis -- I haven't seen that error before.

**Comment by cjvogl** [comment]
Don't merge this yet... there may be a memory leak in the regions module.

**Comment by cjvogl** [comment]
Never mind, the memory issue was coming from my changing of max1d in my local version of amr_module which @mjberger helped to resolve.  These commits should be good to go.

**Comment by mandli** [comment]
The travis build failed due to a problem on their side of things.  I restarted the build, hopefully everything should be fine.

**Comment by cjvogl** [comment]
Thanks for restarting the build.  It looks like it failed again because the Makefiles in the 3d examples don't include the regions module.  Is this something I can change on the Travis end of things?

**Comment by rjleveque** [comment]
I think you will have to modify the Makefiles in all the amrclaw/tests subdirectories since those are the tests that Travis runs.  

Either that or ignore the fact that travis fails for now since this whole branch is work in progress, but it might be useful in finding other bugs as we go along if we keep Travis happy.

**Comment by rjleveque** [comment]
Let's not merge this until after 5.3.0 is released since 3d regions will not be part of this release.

**Comment by mandli** [comment]
Can you by chance rebase this PR to better reflect the actual new code included?

**Comment by cjvogl** [comment]
Will do.  I forgot that this branch was still involved in an active PR before pushing the merge.

**Comment by mandli** [comment]
Makes it complicated.  Also will make it more clear whether the tests failed because of the PR or something else.

**Comment by cjvogl** [comment]
Rebase isn't going well: I'm getting multiple conflicts when trying to squash commits.  Unless there is an objection, it may be easier to just close this PR and open a new one.

**Comment by mandli** [comment]
I would vote close and open a new one maybe mentioning this one so you get the history of the comments.

**Pull request closed without merging**
