### PR TITLE
Cpu Timing

### PR DESCRIPTION
**Pull request by ortegagingrich**
Adds CPU timing (in addition to the existing wall timing) to the 2D and 3D amrclaw packages.  It also improves (I think) the display of the timing results.

Sample Output:
```
 Done integrating to time    3.0000000000000000     

========================== Timing Data ==========================

Using 11 thread(s)

Note: The CPU times are for all threads.

Total time to solution 
Wall Time:     121.23500000 seconds
CPU Time:      454.13238200 seconds

Integration Time (advanc)
Level                   Wall Time                CPU Time
  1                 4.20700000 seconds      4.83230300 seconds
  2                45.52400000 seconds     47.61497400 seconds
  3                63.18300000 seconds    391.55247200 seconds
all (bound)         0.35000000 seconds      3.64023100 seconds
all (stepgrid)    112.51700000 seconds    439.78748600 seconds

Total regridding time 
Wall Time:       0.58000000 seconds
CPU Time:        0.90405600 seconds

=================================================================


==> runclaw: Finished executing

```

### CODE REVIEW

**Comment by rjleveque** [comment]
Thanks Jacob!  

All our travis tests are failing at the moment due to a glitch in our travis scripts that we're working on fixing, so no need to worry about this at the moment.

One suggestion -- maybe the regridding time should be arranged in the table so wall time and cpu time show up in columns 2 and 3 with a shorter label like `all (regridding)`?

**Comment by mjberger** [comment]
Looks good.  I would suggest adding timings for output (valout is more expensive than one would think), and for setaux (ditto on this one, especially until the coping of aux arrays is implemented.)

**Comment by ortegagingrich** [comment]
I have added valout and setaux timings (both wall and cpu) for both the 2d and 3d versions.

**Comment by rjleveque** [comment]
Another suggestion... currently the `_output/fort.amr` file contains some information at the very end, e.g.

```
number of cells advanced for time integration =       6028448.000000
   # cells advanced on level    1 =            300000.00
   # cells advanced on level    2 =           1359744.00
   # cells advanced on level    3 =           4368704.00
number of cells advanced for error estimation =          6856.000000

 percentage of cells advanced in time  =      99.89
 maximum Courant number seen =       0.90
```
(I'm not sure why the number of cells are output as floats rather than integers.)

It might be nice to add another column to the table of timings that lists the total number of cells advanced on each level.    The number advanced for error estimation should probably be zero when Richardson extrapolation isn't used (I'm not sure why it isn't in this example, but may be related to #142?).

Also, it would be good to print out the timing information also to `fort.amr` as well as (or instead of?) to the screen.  That way it can still be examined at a later date.

**Comment by mjberger** [comment]
it’s a float so it doesn’t overflow.

**Comment by rjleveque** [comment]
Shouldn't we just use
`integer (kind=8)`

**Comment by mjberger** [comment]
No problem with that.     That piece of  code predates kind=8.  But as long as you’re in the neighborhood go ahead. 

But in general I think there more important things to refactor.

Marsha

**Comment by ortegagingrich** [comment]
I am afraid that there are several issues that may greatly complicate the timing of setaux().

1) Which calls to setaux should be timed? 

Since amrclaw does not currently collect setaux() timing data, I had to add this myself.  I did this rather naively be searching the src/ directories for any calls to setaux and placing timers around them.  This is the approach which geoclaw (which does collect wall timing data for setaux()) takes.  However, I noticed that the existing geoclaw does not have timers around all calls to setaux().  For example, in filpatch.f90 (in geoclaw/src/2d/shallow/), we have
```
call system_clock(clock_start, clock_rate)
. . .
call setaux(nghost_patch, . . . )
call system_clock(clock_finish, clock_rate)
clock_dif = clock_finish - clock_start
!$OMP ATOMIC
timeSetaux = timeSetaux + clock_dif
```
whereas in ginit.f, no such timing is recorded.  Even more inconsistency can be found in filval.f90, which contains three calls to setaux(), only one of which is actually timed.  In the modifications I made yesterday, I placed timers around each call to setaux in the amr source code; however, there might, perhaps, be a reason for the apparent inconsistencies in how the timing is handled in geoclaw?

2) Multi-thread issues

Not all of the calls to setaux() in geoclaw that include timers update timeSetaux in a thread-safe manner.  It should be determined which calls could possibly be executed by multiple threads at once.  Also, the existing code would be expected to result in an incorrect recording of the wall time, as each thread will add its own wall time to the total.  Thus, if ten threads are used, we would expect the reported wall time for timeSetaux to be about ten times the actual value.  The modifications I made yesterday to the AMR library inherit these multi-thread issues.  In general, I think the best approach would be simply to take timing data only in serial portions of the code.  This would appear to rule out the possibility of timing setaux individually.

In brief, I think that it would not be quite so simple to record setaux timing data correctly.  I think that the corresponding data which geoclaw purports to collect is at best, misleading, and at worst, simply incorrect.  I am inclined simply to leave it out of this pull request.

**Comment by mjberger** [comment]
at one point I had timers in setaux that were atomic, to see how much difference it would make if we implemented copying of setaux arrays from existing grids,  instead of calling anew each time. That seems to have disappeared.

ginit doesn't matter, since it is only called once.

b4step could be important, but since I never used it I overlooked it.  

It is an expensive part of the regridding, so it might still be worth finding out just how much.

**Comment by rjleveque** [comment]
I think there are two ways in which timing information is useful:

- For normal users, it's nice to have a summary at the end of how much wall time and CPU time was used on each level, and total number of cells advanced.  It's good to have that saved in fort.amr as well as output to the screen since for long runs it's often nice to look back at see how long a previous run took.  But most users (including myself most of the time) don't care about a breakdown between different routines.  

- For developers, when trying to improve some part of the code, much more detailed timing info may be needed.  But what's needed may depend on what's being worked on and it seems like a tool such as `gprof` might be more appropriate than complicating the code everywhere putting in timings of every possible thing, particularly if there are subtleties of the sort Jacob has found.

So my suggestion is we keep it simple in the master branch at least, and just report overall timings on each level and not try to instrument calls to setaux.

**Comment by mandli** [comment]
+1 for the KISS approach.

**Comment by ortegagingrich** [comment]
Sorry for the delay.  I think that I have addressed most of what has been brought up.

1) I would prefer to keep the table specific to timings inside of advanc (i.e. stepgrid and bound), keeping the other timings (regridding and valout) separate.  If there are strong opinions otherwise, though, this could be changed.

2) I have removed the code outputting setaux timing data, though I have not removed the timers themselves.  One interested in seeing how much time spent on setaux (or any other individual function) is probably best off using gprof.

3) The most recent commit does print the total regridding and output (valout) times, as I think that it is possible that a user might be interested in these (especially the latter) and these timings are not as problematic as the setaux timings.

4) I have added a column to the advanc table displaying the number of cells at each level.  I am not sure if the total number advanced for error estimation is appropriate data for this section, though, so I have not included it.

5) The existing code already outputs the timing data to fort.amr.  I have, however, cleaned up the format of the data written to the file to match what is written to the console.

Let me know if there are any objections to any of this or further suggestions.

**Comment by mandli** [comment]
This looks good to me save for the decimal in the cells field which seems superfluous.  I am also curious, and maybe this was what you were talking about above, would there ever be a difference between the `bound` count and the `stepgrid` count?

**Comment by ortegagingrich** [comment]
No, those are both the total number of cells (all levels).  Perhaps that should be clarified?

**Comment by mandli** [comment]
At least we should document what each of these mean.  If they are expected to be the same maybe we could omit one of them as well unless it seems like a good idea to provide a check.

**Comment by rjleveque** [comment]
It looks good to me, but I wonder if it makes sense to split out `bound` and `stepgrid` if it's generally true that `stepgrid` accounts for almost all the time?  What exactly is `bound` timing?

Also, perhaps the line
```
Note: The CPU times are for all threads.
```
would be slightly clearer as
```
Note: The CPU times are summed over all threads.
```

**Comment by mjberger** [comment]
bound has the potential to have a lot of overhead.- When you make a lot of small grids, all that setting of  interior bc’s are what  you’re timing.

**Comment by ortegagingrich** [comment]
I think I should clarify what exactly is displayed in the table so that we might perhaps decide on a better less ambiguous way of displaying it.

There are a total of four calls to system_clock and cpu_time inside of advanc: at the beginning, right after bound is called, right before stepgrid is called and at the very end.  Each time that advanc is called, the time difference between the first and last call to system_clock/cpu_time is added to the tvoll(level) (which is from the amr_module), which keeps track of the cumulative time spent in advanc at the current level.  The time difference between the second call and the first is added to timeBound (also in the amr_module) and the difference between the last and third to timeStepgrid.  My idea (which apparently does not seem to have been the best choice) was to include the times for bound and stepgrid in the same table, as they represent timings taken of the two most expensive parts of advanc.

When it was suggested that the cell counts should be included in the table, I figured that, since the times collected for stepgrid and bound represent times across all levels, the corresponding entries in the cells column should be the total number of cells.  There is no way the numbers displayed could be different, as they both come from the same variable (rvol).  Perhaps it might be easier simply to leave one of them blank?

**Comment by mandli** [comment]
I think leaving the bound count out is fine.

**Comment by donnaaboise** [comment]
This will be very useful.  I am currently doing timings between AMRClaw and ForestClaw.    One question I have had, is,   Does regridding include the time spent in filling ghost cells?   It would be interesting (for me at least ) to see the timing results for filling ghost cells split out from regridding.

**Comment by mjberger** [comment]
Regridding shouldn’t include time for ghost cells!   To my mind, only flagging for refinement, making new grids, and  initializing them, should count as regridding time.

Ghost cell filling used to be separately timed in “bound” time, but haven’t checked the rewrite to see where it’s counted.  


Marsha

**Comment by ortegagingrich** [comment]
Sorry, but is there any consensus on what should or should not be displayed.  My impression was (at least talking to Randy a while back) that it was decided that for most non-basic timings, using a profiling tool might be a better approach than to clutter the code further with timers.  As a reminder, currently output looks like this:

```
========================== Timing Data ==========================

Using  6 thread(s)

Note: The CPU times are summed over all threads.

Total time to solution 
Wall Time:           6.6330 seconds
CPU Time:           28.1700 seconds

Integration Time (advanc)
Level                 Wall Time            CPU Time            Cells
  1                  0.219 seconds       1.287 seconds     196800. cells
  2                  0.345 seconds       2.079 seconds    1025088. cells
  3                  3.244 seconds      19.200 seconds   25913264. cells
all (bound)          0.452 seconds       2.675 seconds
all (stepgrid)       3.262 seconds      19.273 seconds   27135152. cells

Total regridding time 
Wall Time:           0.4990 seconds
CPU Time:            2.8431 seconds

Total output (valout) time 
Wall Time:           2.3330 seconds
CPU Time:            2.6669 seconds


=================================================================
```
I think that Randy suggested that perhaps even the bound and stepgrid sub-measurements should be omitted?  I would not recommend removing anything else, though, as the regrid and valout times are import, I think, for a user trying to determine the cost of using adaptive mesh refinement and outputting frequently.

Jacob Ortega-Gingrich

**Comment by donnaaboise** [comment]
I agree - regretting shouldn't probably include fill ghost cells.  But then since I didn't see that timed anyplace else, I assumed it was part of regridding.   I guess I never understood what "bound" was really doing ....  

As for profiling, I used to use gprof all the time in Linux, but it isn't available in OSX.  I think the tool to use is Instruments, but it is hard to get working.   In ForestClaw, we actually have quite a few timers.   In some ways, this is more convenient than going into a  profiler (although both should probably be used), if all you want it basic info about time spent regridding, creating new grids, filling ghost cells, output, etc.

**Comment by mandli** [comment]
I agree with @donnaaboise, basic timings is great to have and I think @ortegagingrich has done a great job in formatting and timing everything.  Beyond the regrid timing are there any other issues that people see?

**Comment by mjberger** [comment]
I find profilers not that illuminating, even on linux.  If I really want to know the cost of just one thing I time it too
 
Bound stands for boundary conditions - both internal and external are handled there. 
Maybe a better name is BC?

Marsha

**Comment by mjberger** [comment]
Stepgrid is only integration time.

Bound is almost all “overhead”, since the more grids you have for parallelism, the most duplicate ghost cells you have.

So I think bound has useful info.  

Marsha

**Comment by rjleveque** [comment]
I'm ok with leaving all the current information in, but can I perhaps suggest a slightly different format, e.g. 

```
========================== Timing Data ==========================

Integration Time (advanc)
Level                 Wall Time            CPU Time            Cells
  1                  0.219 seconds       1.287 seconds     196800. cells
  2                  0.345 seconds       2.079 seconds    1025088. cells
  3                  3.244 seconds      19.200 seconds   25913264. cells

All levels:

stepgrid             3.262 seconds      19.273 seconds   27135152. cells
BCs / ghost cells    0.452 seconds       2.675 seconds
Regridding           0.499 seconds       2.843 seconds
Output (valout)      2.333 seconds       2.667 seconds

Total time:          6.633 seconds      28.170 seconds
Using  6 thread(s)

Note: The "CPU Times" are summed over all threads.
      "Total time" includes more than the routines broken out above
===================================================================
```

As long as there are columns for wall time and CPU time separately, it seems sensible and more compact to use these for all categories rather than formatting some things differently.  I also suggested reordering the way things get listed, in particular so that total time is at the bottom.

It's not going to be clear to users what the difference is between `stepgrid` and `advanc`, or why the three levels of `advanc` add up to more than the `stepgrid` entries.  Would it make more sense to list the total `advanc` time rather than `stepgrid`?  (or conversely the individual levels for `stepgrid` rather than `advanc`)?  In principle there's more information here by listing something different rather than having things for the 3 levels just add up to the total, but in this case we need to explain somewhere what's being counted in `advanc` that's not in `stepgrid` or at least label it something different than `integration time`?

**Comment by ortegagingrich** [comment]
The output format now matches the most recent suggestion by @rjleveque.

**Comment by mandli** [comment]
Thanks @ortegagingrich, can we merge this?

**Comment by ortegagingrich** [comment]
I think that it is ready, if there is a consensus that the current format and information is fine.  Once it is merged, I will submit a pull request with the same changes for geoclaw.

**Comment by mandli** [comment]
If no one minds I will merge this in by tomorrow then.

**Comment by rjleveque** [comment]
Sorry, but another thought:  The f9.3 format now used for BCs / ghost cells will overflow if a run is longer than about 28 hours, which is often true in some applications, at which point it will print `*********` instead of something useful in cases where timings might be of most interest.  I suggest shifting all the columns a bit so it can be at least f12.3 everywhere, and perhaps even switching to scientific notation such as e12.3.  I'm fine with sticking to the more readable f12.3 (fine for jobs that take less than 3 years of CPU time) unless someone feels strongly otherwise.

I think we should wait to merge until @mjberger and @donnaaboise chime in on this format.  (Donna's on Mt. Baker today, will be in Seattle by tomorrow so we can chat about it.)  Also I'd like to hear Marsha's opinion on `advanc` vs. `stepgrid` timings.

**Comment by ortegagingrich** [comment]
I fixed the format for the bound timer.  Sorry about that.

**Comment by mjberger** [comment]
There are a few other formats that need fixing, now that very large (i.e. integer*8 storage) is being used. They are in outtre/outmsh.

Maybe we can fix them all at once, say this weekend.

Marsha

**Comment by rjleveque** [comment]
Also I suggest we change the number of cells in the third column to floating point format to avoid running out of space for it on bigger / longer runs, e.g. e12.3.

**Comment by mjberger** [comment]
I think we’ve come full circle on this one!

**Pull request merged**
