### PR TITLE
One line change in format string to be compatible when >15000 grids are needed

### PR DESCRIPTION
**Pull request by cjvogl**
This should be backwards compatible...

### CODE REVIEW

**Comment by rjleveque** [comment]
If there are that many patches, then the number of grid cells might exceed the `i8` format limit, so maybe bump that up as well?

**Comment by mjberger** [comment]
I'm planning to make this auto-enlarge, the way we do for alloc  memory, when we meet next week.

Please make it big enough to handle 300,000 grids, for example.

 — Marsha

**Comment by mjberger** [comment]
sure make it bigger.   How about changing outmsh format statement for integer coordinates at same time.

 — Marsha

**Comment by rjleveque** [comment]
@mjberger: Can you be more specific?  `outmsh.f` has a bunch of format statements, which are ancient Fortran 66 Hollerith formatted.  

It would be great to rewrite and modernize all these if you'd like to do so.

**Comment by mjberger** [comment]
skip it then leaving it for next hackathon.   

 — Marsha

**Comment by rjleveque** [comment]
I just noticed this message only prints about level 1 grids. 

@cjvogl: Do you really have this many grids at level 1?

When we do update the format statement, we should also do so in 1d and 3d versions.

**Comment by rjleveque** [comment]
This apparently only came up in debugging so we are closing the issue.

**Pull request closed without merging**
